# Site settings
title: heappush
description: > # this means to ignore newlines until "baseurl:"
  Christian Neumüller's Blog: Mostly about software development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oberon00.github.io" # the base hostname & protocol for your site
email: cn00@gmx.at
twitter_username: zeitferne
github_username:  Oberon00

# Build settings
markdown: kramdown
highlighter: pygments
encoding: utf-8
exclude: [Gemfile, Gemfile.lock]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
